import { getCollection } from "astro:content";
import type { StarlightRouteData } from '@astrojs/starlight/route-data';

import { sortPagesByModifiedDate, getPagePath } from "@config/contentUtils";

type AutogeneratedSidebarLink = {
    type: "link";
    label: string;
    href: string;
    autogenerate: {
        directory: string;
    };
};

function isAutogeneratedLink(
    entry: StarlightRouteData["sidebar"][number]
): entry is StarlightRouteData["sidebar"][number] & AutogeneratedSidebarLink {
    return (
        entry.type === "link" &&
        "href" in entry &&
        "autogenerate" in entry &&
        typeof entry.autogenerate === "object" &&
        entry.autogenerate !== null &&
        "directory" in entry.autogenerate
    );
}

export async function onRequest(
    context: {
        locals: App.Locals & {
            starlightRoute?: StarlightRouteData;
        };
        url: URL;
    },
    next: () => Promise<Response>
): Promise<Response> {
    const { starlightRoute } = context.locals;

    if (!starlightRoute?.sidebar) {
        return next();
    }

    const path = context.url.pathname;

    // Sort guide pages by their modify date
    // if statement is here to make sure its not getting the entire guides collection on every load unnecessarily
    // /docs, /guides, and any guides subpages are where we expect to need to sort this
    // both for the sidebar and for the list of guides on the /guides/ landing page
    if (
        path === "/docs" ||
        path === "/docs/" ||
        path === "/guides" ||
        path.startsWith("/guides/")
    ) {
        const guidePages = sortPagesByModifiedDate(
            await getCollection("docs", ({ id, data }) => {
                return id.startsWith("guides/") && !data.draft;
            })
        );

        const guideOrder = new Map(
            guidePages.map((page, index) => [
                getPagePath(page),
                index,
            ])
        );

        const guideEntries = starlightRoute.sidebar
            .filter(isAutogeneratedLink)
            .filter((entry) => entry.autogenerate.directory === "guides")
            .sort((a, b) => {
                const orderA =
                    guideOrder.get(a.href) ?? Number.MAX_SAFE_INTEGER;
                const orderB =
                    guideOrder.get(b.href) ?? Number.MAX_SAFE_INTEGER;

                return orderA - orderB;
            });

        let guideIndex = 0;

        starlightRoute.sidebar = starlightRoute.sidebar.map((entry) => {
            if (
                isAutogeneratedLink(entry) &&
                entry.autogenerate.directory === "guides"
            ) {
                return guideEntries[guideIndex++];
            }

            return entry;
        });
    }

    return next();
}