import { getCollection } from "astro:content";
import type { StarlightRouteData } from '@astrojs/starlight/route-data';

import { sortPagesByModifiedDate, getPagePath } from "../contentUtils";

type AutogeneratedSidebarLink = {
    type: "link";
    label: string;
    href: string;
    autogenerate: {
        directory: string;
    };
};

function isAutogeneratedLink(
    entry: StarlightRouteData["sidebar"][number]
): entry is StarlightRouteData["sidebar"][number] & AutogeneratedSidebarLink {
    return (
        entry.type === "link" &&
        "href" in entry &&
        "autogenerate" in entry &&
        typeof entry.autogenerate === "object" &&
        entry.autogenerate !== null &&
        "directory" in entry.autogenerate
    );
}

export async function onRequest(
    context: {
        locals: App.Locals & {
            starlightRoute?: StarlightRouteData;
            t?: (key: string) => string;
        };
        url: URL;
    },
    next: () => Promise<Response>
): Promise<Response> {
    const { starlightRoute, t } = context.locals;

    if (!starlightRoute?.sidebar || !t) {
        return next();
    }

    const path = context.url.pathname;
    const tagsLabel = t('starlightTags.popularTags');

    // Sort guides by guideOrder
    if (path === "/guides/" || path.startsWith("/guides/")) {
        const guidePages = sortPagesByModifiedDate(
            await getCollection("docs", ({ id, data }) => {
                return id.startsWith("guides/") && !data.draft;
            })
        );

        const guideOrder = new Map(
            guidePages.map((page, index) => [
                getPagePath(page),
                index,
            ])
        );

        const guideEntries = starlightRoute.sidebar
            .filter(isAutogeneratedLink)
            .filter((entry) => entry.autogenerate.directory === "guides")
            .sort((a, b) => {
                const orderA =
                    guideOrder.get(a.href) ?? Number.MAX_SAFE_INTEGER;
                const orderB =
                    guideOrder.get(b.href) ?? Number.MAX_SAFE_INTEGER;

                return orderA - orderB;
            });

        let guideIndex = 0;

        starlightRoute.sidebar = starlightRoute.sidebar.map((entry) => {
            if (
                isAutogeneratedLink(entry) &&
                entry.autogenerate.directory === "guides"
            ) {
                return guideEntries[guideIndex++];
            }

            return entry;
        });
    }

    // Author profiles use their own sidebar and should not show Popular Tags
    if (path.startsWith('/authors/')) {
        starlightRoute.sidebar = starlightRoute.sidebar.filter(
            (entry) => entry.label !== tagsLabel
        );
    }

    // Tag pages should only show the sidebar provided by starlight-tags
    if (path === '/tags/' || path.startsWith('/tags/')) {
        starlightRoute.sidebar = starlightRoute.sidebar.filter(
            (entry) => entry.label === tagsLabel
        );
    }

    return next();
}